### ISSUE TITLE
Node provides the UI a SimpleTP URL instead of SmartTP

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-node#122]
The URL is "Get Data" tab is for plain HTTP protocol:
![image](https://github.com/user-attachments/assets/722904b6-bbbf-42ac-8800-de3a969fb2f4)

This will result in an inefficient download.

Should be changed to `odf+https` to use ODF SmTP.

We should also consider in future banning SiTP or somehow redirecting to SmTP automatically.

**Comment by s373r** [comment]
Done by https://github.com/kamu-data/kamu-cli/pull/812
