### ISSUE TITLE
Replace env vars with config parameters

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-node#45]
Currently `api-server` is configured through 3 different paths:
- `datasetRepositoryUrl` is provided via command line arguments
- `GITHUB_CLIENT_ID / SECRET` and `JWT_SECRET` are provided via env vars
- auth configuration is provided via YAML config file

This ticket is to unify configuration around the YAML config file.

Our config library [figment](https://docs.rs/figment/latest/figment/) already supports overriding config via env vars.

Keeping all config in one place also will allow us to start generating config schemas that can be embedded into helm charts for validation and documentation purposes.

### Steps

- Initial changes
  - [x] `[kamu-cli]` https://github.com/kamu-data/kamu-cli/pull/621
    - [x] `[kamu-cli]` https://github.com/kamu-data/kamu-cli/pull/622
    - [x] `[kamu-cli]` https://github.com/kamu-data/kamu-cli/pull/623
  - [x] `[kamu-node]` https://github.com/kamu-data/kamu-node/pull/81
  - [x] `[helm-charts]` https://github.com/kamu-data/helm-charts/pull/28
  - [x] `[helm-charts]` https://github.com/kamu-data/helm-charts/pull/29
  - [x] `[kamu-deploy]` https://github.com/kamu-data/kamu-deploy/pull/96
- [x] Fixes
  - [x] `[kamu-node]` https://github.com/kamu-data/kamu-node/pull/83
  - [x] `[helm-charts]` https://github.com/kamu-data/helm-charts/pull/31
  - [x] `[kamu-deploy]` https://github.com/kamu-data/kamu-deploy/pull/98
  - [x] `[kamu-deploy]` https://github.com/kamu-data/kamu-deploy/pull/99
- [x] `[kamu-deploy-example]` https://github.com/kamu-data/kamu-deploy-example/pull/3

**Comment by zaychenko-sergei** [comment]
There is an alternative library that seems to be more popular: [config](https://crates.io/crates/config)

**Comment by s373r** [comment]
The final sub-task has been finished, this issue can be closed
