### ISSUE TITLE
API Access Tokens

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-node#59]
## Scope
- No expiration, but revokable
- No token usage tracking
  - In future we can track usage by token
  - and potentially allow drilling down into billing costs by token
- No permission scopes
  - All tokens are read & write - equivalent to the logged in owner account

## Dependencies
- Database
- Accounts

## Tasks
- Create a repo for generated tokens `(account, token_name, token)`
- Transport tokens in standard HTTP headers
- Auth middleware can resolve such token to subject
- New sections in account settings UI to
  - create new token
  - see the list of token names
  - ability to revoke/delete tokens

**Comment by zaychenko-sergei** [comment]
@sergiimk Should we configure permissions scope in UI?

**Comment by sergiimk** [comment]
@zaychenko-sergei clarified the epic's scope:
> - No permission scopes
>   - All tokens are read & write - equivalent to the logged in owner account

**Comment by sergiimk** [comment]
Acceptance testing results:

1) Bug found: https://github.com/kamu-data/kamu-node/issues/115

2) Current account settings are a bit confusing with so many tabs but only a few working:

![image](https://github.com/user-attachments/assets/8a77d296-becc-4a9f-997a-4b12659eff56)

We should mark the tabs that are not yet implemented as "disabled". 

3) "Show revoked tokens" switch works very counter intuitively. It hides active tokens when switched ON, and displays active and revoked tokens when OFF.

![image](https://github.com/user-attachments/assets/f3b0a54a-afd1-46e0-8e24-1a3d72252e4c)

I think revoked tokens should be not visible by default (switch OFF) and when ON: both active and revoked tokens should be shown. Also related to 5).

4) Minor: "Show revoked tokens" should be center-aligned with the button next to it, currently it alignes to the top

5) Revoked tokens cause name conflicts:
![image](https://github.com/user-attachments/assets/9fc1acea-9e91-4bdc-8ce1-64b71dace5df)
![image](https://github.com/user-attachments/assets/1b242c37-86d2-4616-947f-b4437e5a2f53)

Thus if you created `"dev"` token and revoked it - you will never be able to create `dev` token again, which is inconvenient.

Ideally aliases should only conflict between the active tokens.

**Comment by sergiimk** [comment]
Testing results:

Everything working as expected.

All above mentioned issues were fixed except 2) which has a PR but wasn't released yet.

Considering epic completed!

Congrats @rmn-boiko @dmitriy-borzenko !
